from datetime import date, datetime
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class WorkoutReportSection(BaseModel):
    workouts_completed: int = Field(0, description="Total workout sessions completed in period")
    target_workouts: Optional[int] = Field(None, description="Planned workout target for period")
    completion_rate_pct: Optional[float] = Field(None, description="Workout target completion percentage")
    total_duration_minutes: Optional[int] = Field(None, description="Total workout duration in minutes")
    total_sets_completed: Optional[int] = Field(None, description="Total exercise sets completed")
    total_exercises_completed: Optional[int] = Field(None, description="Unique exercises completed")
    most_frequent_muscles: List[str] = Field(default_factory=list, description="Top targeted muscle groups")
    has_data: bool = Field(False, description="True if workout logs exist for period")


class NutritionReportSection(BaseModel):
    logged_days_count: int = Field(0, description="Number of days with logged meals")
    total_days_in_period: int = Field(0, description="Total days in report period")
    logging_completion_pct: float = Field(0.0, description="Percentage of days with logged meals")
    target_calories: Optional[float] = Field(None, description="Daily target calories")
    average_calories_per_logged_day: Optional[float] = Field(None, description="Average daily calories on logged days")
    target_protein_g: Optional[float] = Field(None, description="Daily target protein in grams")
    average_protein_per_logged_day: Optional[float] = Field(None, description="Average daily protein in grams on logged days")
    calorie_adherence_pct: Optional[float] = Field(None, description="Calorie target adherence percentage")
    protein_adherence_pct: Optional[float] = Field(None, description="Protein target adherence percentage")
    has_data: bool = Field(False, description="True if meal logs exist for period")


class ProgressReportSection(BaseModel):
    starting_weight_kg: Optional[float] = Field(None, description="Weight at start of period")
    ending_weight_kg: Optional[float] = Field(None, description="Weight at end of period")
    weight_change_kg: Optional[float] = Field(None, description="Net weight change in kg")
    starting_body_fat_pct: Optional[float] = Field(None, description="Body fat % at start of period")
    ending_body_fat_pct: Optional[float] = Field(None, description="Body fat % at end of period")
    body_fat_change_pct: Optional[float] = Field(None, description="Net body fat % change")
    measurement_count: int = Field(0, description="Number of measurements recorded in period")
    has_data: bool = Field(False, description="True if measurement data exists for period")


class FitnessScoreReportSection(BaseModel):
    starting_score: Optional[int] = Field(None, description="Fitness score at start of period")
    ending_score: Optional[int] = Field(None, description="Fitness score at end of period")
    score_change: Optional[int] = Field(None, description="Net fitness score change")
    trend: Optional[str] = Field(None, description="'improving', 'declining', 'stable', or null")
    has_data: bool = Field(False, description="True if fitness score is available")


class FitnessReportResponse(BaseModel):
    report_type: str = Field(..., description="'weekly' or 'monthly'")
    start_date: date = Field(..., description="Report start date")
    end_date: date = Field(..., description="Report end date")
    generated_at: datetime = Field(..., description="Timestamp when report was generated")
    
    headline: str = Field(..., description="Human-readable title for the report period")
    adherence_score: Optional[float] = Field(None, description="Overall deterministic adherence score (0-100)")
    adherence_label: Optional[str] = Field(None, description="'High', 'Moderate', 'Low', or 'Insufficient Data'")
    adherence_breakdown: Optional[Dict[str, Any]] = Field(None, description="Breakdown of sub-scores used for adherence")
    summary_facts: List[str] = Field(default_factory=list, description="Key deterministic facts derived from period data")
    
    workouts: WorkoutReportSection
    nutrition: NutritionReportSection
    progress: ProgressReportSection
    fitness_score: FitnessScoreReportSection
    
    narrative: Optional[str] = Field(None, description="Optional AI-generated narrative summary based strictly on facts")
    ai_generated: bool = Field(False, description="True if narrative was generated by AI engine")
